import { getHashCode } from './lib/hash';

/**
 * @brief class representing the commissions generated by an execution.
 * @sa Execution
 */
export class CommissionReport {
  ExecId = '';
  Commission = 0;
  Currency = '';
  RealizedPNL = 0;
  Yield = 0;
  YieldRedemptionDate = 0;

  Equals(other?: CommissionReport): boolean {
    if (other == null) {
      return false;
    } else if (this == other) {
      return true;
    }

    return this.ExecId === other.ExecId;
  }

  GetHashCode() {
    return getHashCode(
      'CommissionReport',
      this.ExecId,
      this.Commission,
      this.Currency,
      this.RealizedPNL,
      this.Yield,
      this.YieldRedemptionDate
    );
  }
}
